config/routes.rb
Rails.application.routes.draw do
  resources :other_competences
  resources :other_taskperformances
  resources :other_positions
  resources :other_perfromeds
  resources :nested_descriptions
  resources :request_trainings
  get 'sup_admin/index'
  resources :oth_positions
  get 'final_step/index'
  resources :notrel_trainings
  resources :rel_trainings
  resources :nested_trainings
  resources :other_competencies
  resources :other_tasks
  resources :req_trainings
  resources :nested_othperformes
  resources :nested_othperformeds
  resources :nested_taskperformances
  resources :taskperformances
  resources :competencies
  resources :oth_tasks
  resources :oth_competencies

  resources :req_competencies
  resources :task_perfomances
  get 'home/index'
  get 'admin_index', to: 'admin#index'
  get 'admin_dashboard', to: 'admin#dashboard'
  get 'admin_archieve', to: 'admin#archieve'


  get '/emp_details/new', to: 'emp_details#new', as: 'emp_details_new'

  get '/emp_details/:id/edit', to: 'emp_details#edit', as: 'emp_details_edit'
  get '/jb_decriptions/new', to: 'jb_decriptions#new', as: 'jb_decriptions_new'


  get 'benefits/new', to: 'benefits#new', as: 'benefits_new'
  get 'benefits/index', to: 'benefits#index', as: 'benefits_index'
  resources :jb_performeds
  resources :jb_descriptions
  resources :benefits
  resources :emp_details
  devise_for :users

  resources :final_step do
    member do
      get 'update_submission'

    end
  end


 # Define the custom actions for AdminController outside the resources block
get 'admin/destroy_data/:id', to: 'admin#destroy_data', as: 'admin_destroy_data'
get 'admin/generate_pdf/:id', to: 'admin#generate_pdf', as: 'pdfadmin'
get 'admin/download_excel', to: 'admin#download_excel', as: 'download_excel'
get 'search_users', to: 'admin#search'
get 'destroy_data' => 'final_step#destroy_data', as: :destroy_data_home



# Then, define the resources for admin/user_management as you have it
namespace :admin do
  resources :user_management, only: [:new, :create, :edit, :update, :index] do
    member do
      get :approve_user
      get :archieve_user
      get :restore_user
      get :show_user
      get :unsubmitted_user
    end
  end
end



  resources :home do
    member do
      get 'destroy_data', to: 'home#destroy_data'
      get 'generate_pdf', to: 'home#generate_pdf', as: 'pdf'
    end
  end

  resources :oth_performeds do
    member do
      get 'custom_destroy'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
    # get '/news_session', to: 'users/sessions#news', as: 'news_session'
  end
end

app/models/request_training.rb
class RequestTraining < ApplicationRecord
  belongs_to :req_training

  validates :train_type, :train_benefit, presence: true
end

app/controllers/request_trainings_controller.rb
class RequestTrainingsController < ApplicationController
  before_action :set_request_training, only: %i[ show edit update destroy ]

  # GET /request_trainings or /request_trainings.json
  def index
    @request_trainings = RequestTraining.all
  end

  # GET /request_trainings/1 or /request_trainings/1.json
  def show
  end

  # GET /request_trainings/new
  def new
    @request_training = RequestTraining.new
  end

  # GET /request_trainings/1/edit
  def edit
  end

  # POST /request_trainings or /request_trainings.json
  def create
    @request_training = RequestTraining.new(request_training_params)

    respond_to do |format|
      if @request_training.save
        format.html { redirect_to request_training_url(@request_training), notice: "Request training was successfully created." }
        format.json { render :show, status: :created, location: @request_training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request_training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_trainings/1 or /request_trainings/1.json
  def update
    respond_to do |format|
      if @request_training.update(request_training_params)
        format.html { redirect_to request_training_url(@request_training), notice: "Request training was successfully updated." }
        format.json { render :show, status: :ok, location: @request_training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request_training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_trainings/1 or /request_trainings/1.json
  def destroy
    @request_training.destroy

    respond_to do |format|
      format.html { redirect_to request_trainings_url, notice: "Request training was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_training
      @request_training = RequestTraining.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_training_params
      params.require(:request_training).permit(:train_type, :train_benefit)
    end
end

app/helpers/request_trainings_helper.rb
module RequestTrainingsHelper
end

app/views/request_trainings/_form.html.erb
<%= form_with(model: request_training, class: "contents") do |form| %>
  <% if request_training.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(request_training.errors.count, "error") %> prohibited this request_training from being saved:</h2>

      <ul>
        <% request_training.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :train_type %>
    <%= form.text_field :train_type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :train_benefit %>
    <%= form.text_field :train_benefit, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/request_trainings/_request_training.html.erb
<div id="<%= dom_id request_training %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Train type:</strong>
    <%= request_training.train_type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Train benefit:</strong>
    <%= request_training.train_benefit %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this request training", request_training, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this request training", edit_request_training_path(request_training), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/request_trainings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing request training</h1>

  <%= render "form", request_training: @request_training %>

  <%= link_to "Show this request training", @request_training, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to request trainings", request_trainings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/request_trainings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Request trainings</h1>
    <%= link_to "New request training", new_request_training_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="request_trainings" class="min-w-full">
    <%= render @request_trainings %>
  </div>
</div>

app/views/request_trainings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New request training</h1>

  <%= render "form", request_training: @request_training %>

  <%= link_to "Back to request trainings", request_trainings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/request_trainings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @request_training %>

    <%= link_to "Edit this request_training", edit_request_training_path(@request_training), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this request_training", request_training_path(@request_training), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to request_trainings", request_trainings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>