config/routes.rb
Rails.application.routes.draw do
  resources :other_competences
  resources :other_taskperformances
  resources :other_positions
  resources :other_perfromeds
  resources :nested_descriptions
  resources :request_trainings
  get 'sup_admin/index'
  resources :oth_positions
  get 'final_step/index'
  resources :notrel_trainings
  resources :rel_trainings
  resources :nested_trainings
  resources :other_competencies
  resources :other_tasks
  resources :req_trainings
  resources :nested_othperformes
  resources :nested_othperformeds
  resources :nested_taskperformances
  resources :taskperformances
  resources :competencies
  resources :oth_tasks
  resources :oth_competencies

  resources :req_competencies
  resources :task_perfomances
  get 'home/index'
  get 'admin_index', to: 'admin#index'
  get 'admin_dashboard', to: 'admin#dashboard'
  get 'admin_archieve', to: 'admin#archieve'


  get '/emp_details/new', to: 'emp_details#new', as: 'emp_details_new'

  get '/emp_details/:id/edit', to: 'emp_details#edit', as: 'emp_details_edit'
  get '/jb_decriptions/new', to: 'jb_decriptions#new', as: 'jb_decriptions_new'


  get 'benefits/new', to: 'benefits#new', as: 'benefits_new'
  get 'benefits/index', to: 'benefits#index', as: 'benefits_index'
  resources :jb_performeds
  resources :jb_descriptions
  resources :benefits
  resources :emp_details
  devise_for :users

  resources :final_step do
    member do
      get 'update_submission'

    end
  end


 # Define the custom actions for AdminController outside the resources block
get 'admin/destroy_data/:id', to: 'admin#destroy_data', as: 'admin_destroy_data'
get 'admin/generate_pdf/:id', to: 'admin#generate_pdf', as: 'pdfadmin'
get 'admin/download_excel', to: 'admin#download_excel', as: 'download_excel'
get 'search_users', to: 'admin#search'
get 'destroy_data' => 'final_step#destroy_data', as: :destroy_data_home



# Then, define the resources for admin/user_management as you have it
namespace :admin do
  resources :user_management, only: [:new, :create, :edit, :update, :index] do
    member do
      get :approve_user
      get :archieve_user
      get :restore_user
      get :show_user
      get :unsubmitted_user
    end
  end
end



  resources :home do
    member do
      get 'destroy_data', to: 'home#destroy_data'
      get 'generate_pdf', to: 'home#generate_pdf', as: 'pdf'
    end
  end

  resources :oth_performeds do
    member do
      get 'custom_destroy'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
    # get '/news_session', to: 'users/sessions#news', as: 'news_session'
  end
end

app/models/competency.rb
class Competency < ApplicationRecord
    belongs_to :taskperformance

    validates :competencies, presence: true
end

app/controllers/competencies_controller.rb
class CompetenciesController < ApplicationController
  before_action :set_competency, only: %i[ show edit update destroy ]

  # GET /competencies or /competencies.json
  def index
    @competencies = Competency.all
  end

  # GET /competencies/1 or /competencies/1.json
  def show
  end

  # GET /competencies/new
  def new
    @competency = Competency.new
  end

  # GET /competencies/1/edit
  def edit
  end

  # POST /competencies or /competencies.json
  def create
    @competency = Competency.new(competency_params)

    respond_to do |format|
      if @competency.save
        format.html { redirect_to competency_url(@competency), notice: "Competency was successfully created." }
        format.json { render :show, status: :created, location: @competency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competencies/1 or /competencies/1.json
  def update
    respond_to do |format|
      if @competency.update(competency_params)
        format.html { redirect_to competency_url(@competency), notice: "Competency was successfully updated." }
        format.json { render :show, status: :ok, location: @competency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competencies/1 or /competencies/1.json
  def destroy
    @competency.destroy

    respond_to do |format|
      format.html { redirect_to competencies_url, notice: "Competency was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competency
      @competency = Competency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def competency_params
      params.require(:competency).permit(:competencies)
    end
end

app/helpers/competencies_helper.rb
module CompetenciesHelper
end

app/views/competencies/_competency.html.erb
<div id="<%= dom_id competency %>">
  <p>
    <strong>Competencies:</strong>
    <%= competency.competencies %>
  </p>

</div>

app/views/competencies/_form.html.erb
<%= simple_form_for(@competency) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :competencies %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/competencies/edit.html.erb
<div class="card">
  <h5 class="card-header">Edit competency</h5>
  <div class="card-body">
    <%= render "form", competency: @competency %>
  </div>
</div>

app/views/competencies/index.html.erb
<%= content_tag :h1, "List of Competencies" %>


<div class="text-end mb-3">
  <%= link_to new_competency_path, class: 'btn btn-primary' do %>
    New Competency
  <% end %>
</div>


  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
      <th>#</th>
            <th>Competencies</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
      <% @competencies.each do |competency| %>
        <tr>

        <th scope="row"><%= competency.id %></th>
        <td><%= competency.competencies %></td>
    
          <td>
            <%= link_to 'View', competency, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_competency_path(competency), class: 'btn btn-secondary btn-sm' %>
            <%= link_to "Delete", competency, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

app/views/competencies/new.html.erb
<div class="card">
  <h5 class="card-header">New competency</h5>
  <div class="card-body">
    <%= render "form", competency: @competency %>
  </div>
</div>

app/views/competencies/show.html.erb
<%= render @competency %>

<div>
  <%= link_to "Edit", edit_competency_path(@competency), class: 'btn btn-primary' %> |
  <%= link_to "Back", competencies_path, class: 'btn btn-primary' %>

  <%= button_to "Delete", @competency, method: :delete, class: 'btn btn-danger' %>
</div>