config/routes.rb
Rails.application.routes.draw do
  resources :other_competences
  resources :other_taskperformances
  resources :other_positions
  resources :other_perfromeds
  resources :nested_descriptions
  resources :request_trainings
  get 'sup_admin/index'
  resources :oth_positions
  get 'final_step/index'
  resources :notrel_trainings
  resources :rel_trainings
  resources :nested_trainings
  resources :other_competencies
  resources :other_tasks
  resources :req_trainings
  resources :nested_othperformes
  resources :nested_othperformeds
  resources :nested_taskperformances
  resources :taskperformances
  resources :competencies
  resources :oth_tasks
  resources :oth_competencies

  resources :req_competencies
  resources :task_perfomances
  get 'home/index'
  get 'admin_index', to: 'admin#index'
  get 'admin_dashboard', to: 'admin#dashboard'
  get 'admin_archieve', to: 'admin#archieve'


  get '/emp_details/new', to: 'emp_details#new', as: 'emp_details_new'

  get '/emp_details/:id/edit', to: 'emp_details#edit', as: 'emp_details_edit'
  get '/jb_decriptions/new', to: 'jb_decriptions#new', as: 'jb_decriptions_new'


  get 'benefits/new', to: 'benefits#new', as: 'benefits_new'
  get 'benefits/index', to: 'benefits#index', as: 'benefits_index'
  resources :jb_performeds
  resources :jb_descriptions
  resources :benefits
  resources :emp_details
  devise_for :users

  resources :final_step do
    member do
      get 'update_submission'

    end
  end


 # Define the custom actions for AdminController outside the resources block
get 'admin/destroy_data/:id', to: 'admin#destroy_data', as: 'admin_destroy_data'
get 'admin/generate_pdf/:id', to: 'admin#generate_pdf', as: 'pdfadmin'
get 'admin/download_excel', to: 'admin#download_excel', as: 'download_excel'
get 'search_users', to: 'admin#search'
get 'destroy_data' => 'final_step#destroy_data', as: :destroy_data_home



# Then, define the resources for admin/user_management as you have it
namespace :admin do
  resources :user_management, only: [:new, :create, :edit, :update, :index] do
    member do
      get :approve_user
      get :archieve_user
      get :restore_user
      get :show_user
      get :unsubmitted_user
    end
  end
end



  resources :home do
    member do
      get 'destroy_data', to: 'home#destroy_data'
      get 'generate_pdf', to: 'home#generate_pdf', as: 'pdf'
    end
  end

  resources :oth_performeds do
    member do
      get 'custom_destroy'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
    # get '/news_session', to: 'users/sessions#news', as: 'news_session'
  end
end

app/models/other_taskperformance.rb
class OtherTaskperformance < ApplicationRecord
  belongs_to :other_position

end

app/controllers/other_taskperformances_controller.rb
class OtherTaskperformancesController < ApplicationController
  before_action :set_other_taskperformance, only: %i[ show edit update destroy ]

  # GET /other_taskperformances or /other_taskperformances.json
  def index
    @other_taskperformances = OtherTaskperformance.all
  end

  # GET /other_taskperformances/1 or /other_taskperformances/1.json
  def show
  end

  # GET /other_taskperformances/new
  def new
    @other_taskperformance = OtherTaskperformance.new
  end

  # GET /other_taskperformances/1/edit
  def edit
  end

  # POST /other_taskperformances or /other_taskperformances.json
  def create
    @other_taskperformance = OtherTaskperformance.new(other_taskperformance_params)

    respond_to do |format|
      if @other_taskperformance.save
        format.html { redirect_to other_taskperformance_url(@other_taskperformance), notice: "Other taskperformance was successfully created." }
        format.json { render :show, status: :created, location: @other_taskperformance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @other_taskperformance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /other_taskperformances/1 or /other_taskperformances/1.json
  def update
    respond_to do |format|
      if @other_taskperformance.update(other_taskperformance_params)
        format.html { redirect_to other_taskperformance_url(@other_taskperformance), notice: "Other taskperformance was successfully updated." }
        format.json { render :show, status: :ok, location: @other_taskperformance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @other_taskperformance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /other_taskperformances/1 or /other_taskperformances/1.json
  def destroy
    @other_taskperformance.destroy

    respond_to do |format|
      format.html { redirect_to other_taskperformances_url, notice: "Other taskperformance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_other_taskperformance
      @other_taskperformance = OtherTaskperformance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def other_taskperformance_params
      params.require(:other_taskperformance).permit(:task_notdone, :task_reason, :task_impact)
    end
end

app/helpers/other_taskperformances_helper.rb
module OtherTaskperformancesHelper
end

app/views/other_taskperformances/_form.html.erb
<%= form_with(model: other_taskperformance, class: "contents") do |form| %>
  <% if other_taskperformance.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(other_taskperformance.errors.count, "error") %> prohibited this other_taskperformance from being saved:</h2>

      <ul>
        <% other_taskperformance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :task_notdone %>
    <%= form.text_field :task_notdone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :task_reason %>
    <%= form.text_field :task_reason, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :task_impact %>
    <%= form.text_field :task_impact, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/other_taskperformances/_other_taskperformance.html.erb
<div id="<%= dom_id other_taskperformance %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Task notdone:</strong>
    <%= other_taskperformance.task_notdone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Task reason:</strong>
    <%= other_taskperformance.task_reason %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Task impact:</strong>
    <%= other_taskperformance.task_impact %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this other taskperformance", other_taskperformance, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this other taskperformance", edit_other_taskperformance_path(other_taskperformance), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/other_taskperformances/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing other taskperformance</h1>

  <%= render "form", other_taskperformance: @other_taskperformance %>

  <%= link_to "Show this other taskperformance", @other_taskperformance, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to other taskperformances", other_taskperformances_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/other_taskperformances/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Other taskperformances</h1>
    <%= link_to "New other taskperformance", new_other_taskperformance_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="other_taskperformances" class="min-w-full">
    <%= render @other_taskperformances %>
  </div>
</div>

app/views/other_taskperformances/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New other taskperformance</h1>

  <%= render "form", other_taskperformance: @other_taskperformance %>

  <%= link_to "Back to other taskperformances", other_taskperformances_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/other_taskperformances/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @other_taskperformance %>

    <%= link_to "Edit this other_taskperformance", edit_other_taskperformance_path(@other_taskperformance), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this other_taskperformance", other_taskperformance_path(@other_taskperformance), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to other_taskperformances", other_taskperformances_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>